### ISSUE TITLE
non-free dependencies

### ISSUE THREAD

**Issue by IzzySoft** [Sztorm/NoteCalendar#1]
Not sure if you're aware, but my library scanner just detected that the APK of your app contains non-free libraries:

```
Offending libs:
---------------
* Google Mobile Services (/com/google/android/gms): NonFreeDep

1 offenders.
```

which were most likely dragged in by

```
* Google Play OSS-Licenses (/com/google/android/gms/oss/licenses): UI Component, Apache-2.0
```

This library seems to have some "Trojan effects": claiming itself to be F/LOSS and coming under a free license (Apache-2.0) it is, as almost all libraries starting with `com.google.android.gms`, part of Google Mobile Service and prone to drag in non-free parts of the same. You might hence consider replacing it with a real F/LOSS library. You can find some candidates [here in my snippet](https://gitlab.com/-/snippets/1896503#license-dialogs); with your app using the MIT license, [SimpleLicenseDisplay](https://github.com/MarcDonald/SimpleLicenseDisplay) might be a good match as it uses the same.

Thanks for providing your app as free/libre and open source software – and all the best for the future of your project(s)!

**Comment by Sztorm** [comment]
Thanks for pointing it out, I'm looking forward to replace this dependency as soon as possible.

**Comment by Sztorm** [comment]
Google Play OSS-Licenses dependecy is now replaced, I'm closing this issue soon if no further problems are noticed.

**Comment by IzzySoft** [comment]
Great! That was really fast :star_struck: I've just added your app to my repo a few hours ago (on request of a user), so now I felt obligated to manually trigger the first update for a clean start without any "anti-features" listed. So I hereby happily report a full success: The non-free dependency is gone :partying_face:

Oh, having announced the listing: your app will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.sztorm.notecalendar) with the next sync around 6 pm UTC. Be welcome to pick [a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there from your readme if you like what you'll find there then :smile:

As the issue is solved, I'll close it myself now. Thanks a lot for your quick reaction and prompt fix – also in the name of the F/LOSS community!
