### ISSUE TITLE
Suggestions : remove on step and show the keyboard

### ISSUE THREAD

**Issue by supersarma** [Sztorm/NoteCalendar#5]
Hello,

Just discovered your app and love it. Thank you for your work.
I would suggest something, useful in my opinion. 

When you open the app, you land on the day tab. Fine.
I order to write something, you need to:
1. Click on "Add Note"
2. Click on "Add Text"
3. Click on the empty field in order to show the keyboard 

In my option, it would be better to land the user directly on step 2 (showing directly "Add Text" page).
After clicking on "Add Tex"t, the app could show the keyboard. 

As it removes 2 useless steps, it will probably improve the user experience.

Thank  you.

Enjoy your day.

**Comment by Sztorm** [comment]
Hi,
Thanks for your suggestion, good point on useless steps. If someone wants to add note, obviously also want to add a text to it :D
I think the "Add Note" button will stay, but when you press it, it will direct you to text editor with opened keyboard and text cursor in the first line.
That should be rather easy to implement, and I'll try to do something with it in my free time.

**Comment by Sztorm** [comment]
I just posted a new release of the app with improved day tab interface. It's available on GitHub right now and will soon appear in IzzyOnDroid repository and Google Play Store.

**Comment by Sztorm** [comment]
Implemented in version [1.0.4](https://github.com/Sztorm/NoteCalendar/releases/tag/1.0.4)
