### ISSUE TITLE
Multiple suggestions 

### ISSUE THREAD

**Issue by supersarma** [Sztorm/NoteCalendar#7]
Hi there,

I have some suggestions that I believe will improve the app.
Maybe you have the ability and free time to implement them.

**1. Chose the default view (landing view)**
As  you set the reminder for future days, it seems useless to make the "current day page" as the landing page.
It would be great if, in the settings, we can pick on which view we want to land when starting the app. 
I would definitely pick de first view (full month calendar).

**2. Long Press**
As I said, the full month view is the best view for me. It can be even better with 2 things.
To create an event from this view, we need to click on the date which open the current day tab, and then, click on Add Note...
It would be great if a long press on the date automatically trigg the Add Note. It will remove 1 step.
If the reminder do not exist on the day, trigg de "Add note", otherwise, trigg "Edit note" action. 

Have a god day.

**Comment by Sztorm** [comment]
Hi, good suggestions, I'll try to add them someday.

**Comment by Sztorm** [comment]
Implemented in version [1.0.6](https://github.com/Sztorm/NoteCalendar/releases/tag/1.0.6)

**Comment by supersarma** [comment]
Hi mate. Long time no see !
I updated the app and this new feature works great. 
Thank you very much 🤙
