### ISSUE TITLE
Translate your application.

### ISSUE THREAD

**Issue by franco27** [Sztorm/NoteCalendar#8]
Hello, 
I just discovered your application. 
Apparently, your application has multilingual support. 

On the homepage, I don't see a link for the translation platform or how to do other translations. 

The French language is not available, and I would like to make the French translation. 

Ideally, I would like to do this translation on https://hosted.weblate.org/

Best regards.

**Comment by Sztorm** [comment]
Hi,
Thanks for your desire to translate this application into French.
I have not set up this application on translation platform yet. All current translations are made by translating [strings.xml file](https://github.com/Sztorm/NoteCalendar/blob/master/app/src/main/res/values/strings.xml) into language of choice. I will look into that platform you suggested in my free time.

**Comment by Sztorm** [comment]
I set it up yesterday, here is the [link](https://hosted.weblate.org/projects/note-calendar/). My app will remain here for about 2 weeks, after which the trial will expire unless Hosted Weblate accepts free hosting for my application. During the trial new translations are welcome.

**Comment by UnifeGi** [comment]
I translated it into Romanian!

**Comment by Sztorm** [comment]
@UnifeGi Thank you! I will include Romanian language for today's update.

**Comment by Sztorm** [comment]
Weblate accepted the Libre plan for my app, which means they provide free hosting for Note Calendar translations. That makes sure the translation platform will remain available for you. I think that resolves this issue.
